services:
  postgres:
    image: postgres:17.4
    environment:
    - POSTGRES_DB=icms
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - 5433:5432
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.4
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=P4ssword!
    command:
    - start-dev
    - --import-realm
    volumes:
    - ./keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
    ports:
    - 8085:8080
